duyhuynh55110/rodas

app/Models/Brand.php
app/Modules/Admin/Services/BrandService.php
resources/assets/admin/js/pages/brands/list.js

format code 
**Backlog:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-3](https://duyhuynh55110.atlassian.net/browse/RODAS-3) 
- n/a
* [] DB

feature/RODAS-3: format code

---

app/Models/Product.php
app/Modules/Admin/Config/breadcrumbs.yml
app/Modules/Admin/Config/sidebar.yml
app/Modules/Admin/Http/Controllers/ProductController.php
app/Modules/Admin/Http/Requests/ProductFormRequest.php
app/Modules/Admin/Repositories/CategoryRepository.php
app/Modules/Admin/Repositories/ProductRepository.php
app/Modules/Admin/Resources/views/products/form.blade.php
app/Modules/Admin/Resources/views/products/index.blade.php
app/Modules/Admin/Routes/routes.php
app/Modules/Admin/Services/BrandService.php
app/Modules/Admin/Services/CategoryService.php
app/Modules/Admin/Services/CountryService.php
app/Modules/Admin/Services/ProductService.php
database/factories/ProductFactory.php
database/migrations/2022_08_20_221924_remove_weight_column_in_products_table.php
database/migrations/2022_08_20_222350_add_description_column_to_products_table.php
resources/assets/admin/js/app.js
resources/assets/admin/js/pages/products.js
resources/assets/admin/js/pages/products/form.js
resources/assets/admin/js/pages/products/list.js
resources/assets/admin/scss/app.scss
webpack.mix.js

Product pages
- List
- Create
- Update
**Backlog:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-121](https://duyhuynh55110.atlassian.net/browse/RODAS-12) 
- n/a

feature/RODAS-12: product functions

---

app/Modules/Admin/Resources/views/products/form.blade.php
app/Modules/Admin/Resources/views/products/index.blade.php
resources/assets/admin/js/pages/products.js
resources/assets/admin/js/pages/products/form.js
resources/assets/admin/js/pages/products/list.js

format code , fix bug $product
**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-12](https://duyhuynh55110.atlassian.net/browse/RODAS-12) 
- n/a

feature/RODAS-12: format code, fix bug undefined $product

---

app/Modules/Admin/Resources/views/products/index.blade.php
resources/assets/admin/js/pages/products/list.js

format code 
**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-12](https://duyhuynh55110.atlassian.net/browse/RODAS-12) 
- n/a

feature/RODAS-12: format code

---

app/Http/Kernel.php
app/Models/PersonalAccessToken.php
app/Providers/AppServiceProvider.php
composer.json
composer.lock

format code 
**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-24](https://duyhuynh55110.atlassian.net/browse/RODAS-24) 
- n/a

feature/RODAS-24: Config laravel/sanctum package for app

---

.env.dev
app/Http/Kernel.php
app/Libs/Constants/constants.php
app/Modules/Admin/Routes/routes.php
app/Modules/Api/.gitignore
app/Modules/Api/Http/Middleware/ResponseWithJsonMiddleware.php
app/Modules/Api/Routes/routes.php

- Install 'Api' module
**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-25](https://duyhuynh55110.atlassian.net/browse/RODAS-25) 
- n/a

feature/RODAS-25: [Laravel] install  'Api' module

---

app/Exceptions/Handler.php
app/Libs/Constants/constants.php
app/Libs/Helpers/Helper.php
app/Models/Traits/AdminTimestamp.php
app/Models/User.php
app/Modules/Api/Http/Controllers/Auth/RegisterController.php
app/Modules/Api/Http/Controllers/BaseController.php
app/Modules/Api/Http/Middleware/ResponseWithJsonMiddleware.php
app/Modules/Api/Http/Requests/RegisterUserFormRequest.php
app/Modules/Api/Repositories/UserRepository.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/UserService.php
app/Modules/Api/Transformers/UserTransformer.php
app/Providers/AppServiceProvider.php
composer.json
composer.lock

Docs: https://packagist.org/packages/league/fractal
**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-26](https://duyhuynh55110.atlassian.net/browse/RODAS-26) 
- n/a

feature/RODAS-26: Install 'league/fractal' package to manage API output & make 'register user' API

---

app/Libs/Helpers/Helper.php
app/Modules/Api/Http/Controllers/BaseController.php
app/Modules/Api/Http/Controllers/CompositionController.php
app/Modules/Api/Repositories/CategoryRepository.php
app/Modules/Api/Repositories/GiftBoxRepository.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/CompositionService.php
app/Modules/Api/Services/UserService.php
app/Modules/Api/Transformers/CategoryTransformer.php
app/Modules/Api/Transformers/GiftBoxTransformer.php

format code 
**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-28](https://duyhuynh55110.atlassian.net/browse/RODAS-28) 
- n/a

feature/RODAS-28: Finish composition API for homepage

---

app/Modules/Api/Http/Controllers/BaseController.php
app/Modules/Api/Http/Controllers/CategoryController.php
app/Modules/Api/Http/Controllers/CompositionController.php
app/Modules/Api/Http/Controllers/ProductController.php
app/Modules/Api/Repositories/ProductRepository.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/CategoryService.php
app/Modules/Api/Services/CompositionService.php
app/Modules/Api/Services/ProductService.php
app/Modules/Api/Transformers/BrandTransformer.php
app/Modules/Api/Transformers/ProductTransformer.php

- Code API
**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-29](https://duyhuynh55110.atlassian.net/browse/RODAS-29) 
- n/a

feature/RODAS-29: Done 'categories index' API, 'products index' API

---

app/Libs/Helpers/Helper.php
app/Modules/Admin/Repositories/BrandRepository.php
app/Modules/Admin/Repositories/GiftBoxRepository.php
app/Modules/Admin/Repositories/ProductRepository.php
app/Modules/Admin/Services/BrandService.php
app/Modules/Admin/Services/GiftBoxService.php
app/Modules/Admin/Services/ProductService.php
app/Modules/Api/Http/Controllers/ProductController.php
app/Modules/Api/Http/Requests/ProductsListFormRequest.php
app/Modules/Api/Repositories/ProductRepository.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/ProductService.php
app/Modules/Api/Transformers/ProductTransformer.php

Add search condition to products index API
**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-30](https://duyhuynh55110.atlassian.net/browse/RODAS-30) 
- n/a

feature/RODAS-30: add filter to 'products' API

---

app/Modules/Api/Http/Controllers/ProductController.php
app/Modules/Api/Repositories/ProductRepository.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/ProductService.php
app/Modules/Api/Transformers/CartProductTransformer.php

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-31](https://duyhuynh55110.atlassian.net/browse/RODAS-31) 
- n/a

feature/RODAS-31: Make 'products cart' API

---

app/Modules/Api/Http/Controllers/CartController.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/ProductService.php
app/Modules/Api/Transformers/ProductCartTransformer.php

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-32](https://duyhuynh55110.atlassian.net/browse/RODAS-32) 
- n/a

feature/RODAS-32:  Change 'CartProduct' text -> 'ProductCart' text

---

app/Models/CartProduct.php
app/Models/User.php
app/Modules/Api/Http/Controllers/CartController.php
app/Modules/Api/Http/Requests/CreateProductToCartFormRequest.php
app/Modules/Api/Http/Requests/RemoveProductFromCartFormRequest.php
app/Modules/Api/Repositories/CartProductRepository.php
app/Modules/Api/Repositories/ProductRepository.php
app/Modules/Api/Repositories/UserRepository.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/ProductService.php
app/Modules/Api/Transformers/CartProductTransformer.php

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-33](https://duyhuynh55110.atlassian.net/browse/RODAS-33) 
- n/a

feature/RODAS-33: Make add/update/remove products to cart APIs

---

app/Models/FavoriteProduct.php
app/Models/User.php
app/Modules/Api/Http/Controllers/FavoriteController.php
app/Modules/Api/Http/Controllers/ProductController.php
app/Modules/Api/Http/Requests/CreateFavoriteProductFormRequest.php
app/Modules/Api/Http/Requests/RemoveFavoriteProductFormRequest.php
app/Modules/Api/Repositories/UserRepository.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/ProductService.php

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-34](https://duyhuynh55110.atlassian.net/browse/RODAS-34) 
- n/a

feature/RODAS-34: Make index/add/remove favorite products APIs

---

app/Modules/Api/Http/Controllers/BaseController.php
app/Modules/Api/Http/Controllers/UserController.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/UserService.php

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-35](https://duyhuynh55110.atlassian.net/browse/RODAS-35) 
- n/a

feature/RODAS-35: Make profile API

---

app/Libs/Constants/constants.php
app/Models/UserNotification.php
app/Modules/Api/Http/Controllers/NotificationController.php
app/Modules/Api/Http/Requests/NotificationsListFormRequest.php
app/Modules/Api/Repositories/UserNotificationRepository.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/UserNotificationService.php
app/Modules/Api/Transformers/UserNotificationTransformer.php
database/migrations/2022_11_09_060244_add_type_column_to_user_notifications_table.php

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-36](https://duyhuynh55110.atlassian.net/browse/RODAS-36) 
- n/a

feature/RODAS-36: Make notifications list API

---

app/Modules/Api/Http/Controllers/ProductController.php
app/Modules/Api/Http/Requests/ProductDetailFormRequest.php
app/Modules/Api/Repositories/ProductRepository.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/ProductService.php

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-37](https://duyhuynh55110.atlassian.net/browse/RODAS-37) 
- n/a

feature/RODAS-37: Make product detail API

---

resources/assets/user/src/i18n/en/index.json
resources/assets/user/src/i18n/vn/index.json

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-39](https://duyhuynh55110.atlassian.net/browse/RODAS-39) 
- n/a

feature/RODAS-39: [Vue] Add translate data for i18n

---

resources/assets/user/src/components/items/ItemBoxList/index.vue
resources/assets/user/src/components/layout/Navbar/Navbar.js
resources/assets/user/src/components/ui/ButtonPrimary/ButtonPrimary.js
resources/assets/user/src/components/ui/ButtonPrimary/index.vue
resources/assets/user/src/components/ui/MenuList/index.vue
resources/assets/user/src/components/ui/TitleBar/TitleBar.scss
resources/assets/user/src/scss/base/_reset.scss
resources/assets/user/src/scss/base/_typography.scss
resources/assets/user/src/views/auth/HomeView/index.vue
resources/assets/user/src/views/auth/ShoppingCartView/index.vue
resources/assets/user/src/views/auth/UserMenuView/index.vue
resources/assets/user/src/views/auth/WishListView/index.vue

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-40](https://duyhuynh55110.atlassian.net/browse/RODAS-40) 
- n/a

feature/RODAS-40: Add translate data to layout

---

resources/assets/user/src/App.vue
resources/assets/user/src/router/routes.js

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-41](https://duyhuynh55110.atlassian.net/browse/RODAS-41) 
- n/a

feature/RODAS-41: change page title

---

resources/assets/user/src/App.vue
resources/assets/user/src/components/categories/ItemCategoriesList/ItemCategoriesList.js
resources/assets/user/src/components/categories/ItemCategoriesList/ItemCategoriesList.scss
resources/assets/user/src/components/categories/ItemCategoriesList/index.vue
resources/assets/user/src/components/index.js
resources/assets/user/src/components/items/CartItem/CartItem.scss
resources/assets/user/src/components/items/ItemBox/ItemBox.scss
resources/assets/user/src/components/layout/Navbar/Navbar.js
resources/assets/user/src/components/layout/Navbar/Navbar.scss
resources/assets/user/src/components/layout/Toolbar/Toolbar.scss
resources/assets/user/src/components/posts/PostCard/PostCard.scss
resources/assets/user/src/components/ui/NotificationBar/NotificationBar.scss
resources/assets/user/src/i18n/en/index.json
resources/assets/user/src/i18n/vn/index.json
resources/assets/user/src/main.js
resources/assets/user/src/router/routes.js
resources/assets/user/src/scss/abstracts/_variables.scss
resources/assets/user/src/scss/base/_reset.scss
resources/assets/user/src/scss/base/_typography.scss
resources/assets/user/src/scss/custom/_styles.scss
resources/assets/user/src/scss/layout/_spacing.scss
resources/assets/user/src/views/auth/CategoriesIndexView/CategoriesIndexView.js
resources/assets/user/src/views/auth/CategoriesIndexView/index.vue
resources/assets/user/src/views/auth/CategoriesView/CategoriesView.js
resources/assets/user/src/views/auth/CategoriesView/index.vue
resources/assets/user/src/views/auth/CategoryDetailView/CategoryDetailView.js
resources/assets/user/src/views/auth/CategoryDetailView/CategoryDetailView.scss
resources/assets/user/src/views/auth/CategoryDetailView/index.vue

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-42](https://duyhuynh55110.atlassian.net/browse/RODAS-42) 
- n/a

feature/RODAS-42: Design layout categories index, categories detail pages

---

resources/assets/user/src/components/index.js
resources/assets/user/src/components/layout/LinkIcon/LinkIcon.js
resources/assets/user/src/components/layout/LinkIcon/components/IconBack/IconBack.js
resources/assets/user/src/components/layout/LinkIcon/components/IconBack/index.vue
resources/assets/user/src/components/layout/LinkIcon/components/IconMenu/IconMenu.js
resources/assets/user/src/components/layout/LinkIcon/components/IconMenu/index.vue
resources/assets/user/src/components/layout/LinkIcon/components/index.js
resources/assets/user/src/components/layout/LinkIcon/index.vue
resources/assets/user/src/main.js
resources/assets/user/src/views/auth/CategoriesIndexView/CategoriesIndexView.js
resources/assets/user/src/views/auth/CategoriesIndexView/index.vue
resources/assets/user/src/views/auth/CategoryDetailView/index.vue
resources/assets/user/src/views/auth/NotificationsView/NotificationsView.js
resources/assets/user/src/views/auth/NotificationsView/index.vue
resources/assets/user/src/views/auth/ProfileView/ProfileView.js
resources/assets/user/src/views/auth/ProfileView/index.vue
resources/assets/user/src/views/auth/ShoppingCartView/ShoppingCartView.js
resources/assets/user/src/views/auth/ShoppingCartView/index.vue
resources/assets/user/src/views/auth/UserMenuView/UserMenuView.js
resources/assets/user/src/views/auth/UserMenuView/index.vue
resources/assets/user/src/views/auth/WishListView/WishListView.js
resources/assets/user/src/views/auth/WishListView/index.vue

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-43](https://duyhuynh55110.atlassian.net/browse/RODAS-43) 
- n/a

feature/RODAS-43: Global 'LinkIcon', 'Navbar' components

---

resources/assets/user/src/components/items/ItemBox/ItemBox.js
resources/assets/user/src/components/layout/Toolbar/Toolbar.js
resources/assets/user/src/components/ui/ButtonPrimary/ButtonPrimary.js
resources/assets/user/src/views/auth/CategoriesIndexView/CategoriesIndexView.js
resources/assets/user/src/views/auth/CategoryDetailView/CategoryDetailView.js
resources/assets/user/src/views/auth/ShoppingCartView/ShoppingCartView.js

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-44](https://duyhuynh55110.atlassian.net/browse/RODAS-44) 
- n/a

feature/RODAS-44: Fix export name, change '' to "",

---

app/Libs/Constants/constants.php
resources/assets/user/package-lock.json
resources/assets/user/package.json
resources/assets/user/src/services/base.service.js
resources/assets/user/src/services/products.service.js
resources/assets/user/src/store/index.js
resources/assets/user/src/store/products.js
resources/assets/user/src/utils/constants.js
resources/assets/user/src/views/auth/HomeView/HomeView.js
resources/assets/user/src/views/auth/HomeView/index.vue

- Config store and modules (vuex)
- Config axios: cors, baseUrl
- handle error: 500, 404
**Jira:** 
- [https://duyhuynh55110.atlassian.net/browse/RODAS-4](https://duyhuynh55110.atlassian.net/browse/RODAS-4) 
- n/a

feature/RODAS-45: Config store (Vuex), config axios & handle error 

---

resources/assets/admin/js/pages/gift-boxes/form.js
resources/assets/admin/js/pages/gift-boxes/services/productService.js

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-49](https://duyhuynh55110.atlassian.net/browse/RODAS-49) 
- n/a

feature/RODAS-49: [Laravel] [Admin] fix bug not validate quantity when add products to gift box

---

app/Providers/DataBaseQueryServiceProvider.php
composer.json
composer.lock
config/app.php
config/debugbar.php
storage/debugbar/.gitignore

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-51](https://duyhuynh55110.atlassian.net/browse/RODAS-51) 
- n/a

feature/RODAS-51: [Laravel] Install 'Laravel Debugbar' package to log query on local & log query (DataBaseQueryServiceProvider)

---

app/Modules/Api/Routes/routes.php
resources/assets/user/src/services/favorite.service.js
resources/assets/user/src/store/index.js
resources/assets/user/src/store/views/wishlistView.js
resources/assets/user/src/views/auth/WishListView/WishListView.js
resources/assets/user/src/views/auth/WishListView/index.vue

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-53](https://duyhuynh55110.atlassian.net/browse/RODAS-53) 
- n/a

feature/RODAS-53: Complete 'Wishlish page'

---

resources/assets/user/src/store/views/categories/categoryDetailView.js
resources/assets/user/src/store/views/categories/categoryIndexView.js
resources/assets/user/src/store/views/homeView.js
resources/assets/user/src/store/views/wishlistView.js
resources/assets/user/src/utils/helper.js
resources/assets/user/src/views/auth/HomeView/HomeView.js
resources/assets/user/src/views/auth/WishListView/WishListView.js
resources/assets/user/src/views/auth/categories/CategoryDetailView/CategoryDetailView.js
resources/assets/user/src/views/auth/categories/CategoryIndexView/CategoryIndexView.js

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-55](https://duyhuynh55110.atlassian.net/browse/RODAS-55) 
- n/a

feature/RODAS-55: Reset state when leave page ('unmounted' hook)

---

resources/assets/user/src/components/products/ProductBoxesList/index.vue
resources/assets/user/src/components/ui/ButtonPrimary/ButtonPrimary.js
resources/assets/user/src/i18n/en/index.json
resources/assets/user/src/i18n/vn/index.json
resources/assets/user/src/layouts/AuthLayout/AuthLayout.js
resources/assets/user/src/layouts/AuthLayout/AuthLayout.scss
resources/assets/user/src/layouts/AuthLayout/AuthLayout.vue
resources/assets/user/src/layouts/index.js
resources/assets/user/src/main.js
resources/assets/user/src/router/routes.js
resources/assets/user/src/scss/abstracts/_variables.scss
resources/assets/user/src/scss/base/_reset.scss
resources/assets/user/src/scss/base/_typography.scss
resources/assets/user/src/scss/layout/_spacing.scss
resources/assets/user/src/utils/helper.js
resources/assets/user/src/views/unAuth/LoginView/LoginView.js
resources/assets/user/src/views/unAuth/LoginView/LoginView.vue
resources/assets/user/src/views/unAuth/SignUpView/SignUpView.js
resources/assets/user/src/views/unAuth/SignUpView/SignUpView.vue

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-62](https://duyhuynh55110.atlassian.net/browse/RODAS-62) 
- n/a

feature/RODAS-62: Design SignIn, SignUp pages

---

resources/assets/user/src/utils/helper.js
resources/assets/user/src/views/auth/HomeView/HomeView.js
resources/assets/user/src/views/auth/WishListView/WishListView.js
resources/assets/user/src/views/auth/categories/CategoryDetailView/CategoryDetailView.js
resources/assets/user/src/views/auth/categories/CategoryDetailView/components/SearchBar/SearchBar.js

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-62](https://duyhuynh55110.atlassian.net/browse/RODAS-62) 
- n/a

feature/RODAS-62: fix helper functions

---

app/Exceptions/AuthenticateException.php
app/Exceptions/Handler.php
app/Libs/Constants/constants.php
app/Modules/Api/Http/Controllers/BaseController.php
app/Modules/Api/Routes/routes.php
app/Modules/Api/Services/UserService.php
resources/assets/user/package-lock.json
resources/assets/user/package.json
resources/assets/user/src/layouts/AuthLayout/AuthLayout.scss
resources/assets/user/src/main.js
resources/assets/user/src/router/index.js
resources/assets/user/src/router/routes.js
resources/assets/user/src/scss/abstracts/_variables.scss
resources/assets/user/src/scss/base/_typography.scss
resources/assets/user/src/services/auth.service.js
resources/assets/user/src/services/base.service.js
resources/assets/user/src/store/app.js
resources/assets/user/src/utils/auth.js
resources/assets/user/src/utils/constants.js
resources/assets/user/src/views/unAuth/LoginView/LoginView.js
resources/assets/user/src/views/unAuth/LoginView/LoginView.vue

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-63](https://duyhuynh55110.atlassian.net/browse/RODAS-63) 
- n/a

feature/RODAS-63: Install 'vee-validator' package & complete 'Login' page

---

resources/assets/user/src/components/index.js
resources/assets/user/src/components/products/Stepper/Stepper.js
resources/assets/user/src/components/products/Stepper/Stepper.scss
resources/assets/user/src/components/products/Stepper/Stepper.vue
resources/assets/user/src/i18n/en/index.json
resources/assets/user/src/i18n/vn/index.json
resources/assets/user/src/router/routes.js
resources/assets/user/src/scss/abstracts/_mixins.scss
resources/assets/user/src/scss/base/_reset.scss
resources/assets/user/src/scss/base/_typography.scss
resources/assets/user/src/views/auth/products/ProductDetailView/ProductDetailView.js
resources/assets/user/src/views/auth/products/ProductDetailView/ProductDetailView.scss
resources/assets/user/src/views/auth/products/ProductDetailView/ProductDetailView.vue
resources/assets/user/src/views/auth/products/ProductDetailView/components/TabSwiper/TabSwiper.js
resources/assets/user/src/views/auth/products/ProductDetailView/components/TabSwiper/TabSwiper.scss
resources/assets/user/src/views/auth/products/ProductDetailView/components/TabSwiper/TabSwiper.vue

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-66](https://duyhuynh55110.atlassian.net/browse/RODAS-66) 
- n/a

feature/RODAS-66: Design 'product detail' page

---

app/Exceptions/AuthenticateException.php
app/Exceptions/Handler.php
app/Libs/Constants/constants.php
app/Models/Product.php
app/Models/ProductSlide.php
app/Modules/Admin/Http/Controllers/BaseController.php
app/Modules/Admin/Http/Controllers/ProductController.php
app/Modules/Admin/Http/Controllers/StorageController.php
app/Modules/Admin/Http/Requests/ProductFormRequest.php
app/Modules/Admin/Repositories/ProductRepository.php
app/Modules/Admin/Resources/views/products/form.blade.php
app/Modules/Admin/Routes/routes.php
app/Modules/Admin/Services/ProductService.php
app/Modules/Admin/Services/StorageService.php
app/Modules/Api/Http/Controllers/BaseController.php
app/Modules/Api/Http/Requests/NotificationsListFormRequest.php
app/Modules/Api/Repositories/UserNotificationRepository.php
app/Modules/Api/Routes/routes.php
database/factories/UserNotificationFactory.php
database/migrations/2023_01_07_162524_create_product_slides_table.php
package-lock.json
package.json
resources/assets/admin/js/pages/products/form.js
resources/assets/admin/scss/app.scss
resources/assets/admin/scss/pages/products/form.scss
webpack.mix.js

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-69](https://duyhuynh55110.atlassian.net/browse/RODAS-69) 
- n/a

feature/RODAS-69: Complete install dropzone & add upload product slides

---

resources/assets/user/src/views/auth/ProfileView/ProfileView.js
resources/assets/user/src/views/auth/ProfileView/ProfileView.vue
resources/assets/user/src/views/auth/ProfileView/components/ProfileInfo/ProfileInfo.js
resources/assets/user/src/views/auth/ProfileView/components/ProfileList/ProfileList.js

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-70](https://duyhuynh55110.atlassian.net/browse/RODAS-70) 
- n/a

fix_bug/RODAS-70: Fix profile page - error

---

app/Libs/Constants/constants.php
app/Modules/Api/Http/Controllers/FavoriteController.php
app/Modules/Api/Http/Requests/CreateProductToCartFormRequest.php
app/Modules/Api/Repositories/ProductRepository.php
app/Modules/Api/Repositories/UserRepository.php
app/Modules/Api/Services/ProductService.php
resources/assets/user/package-lock.json
resources/assets/user/package.json
resources/assets/user/src/components/layout/Toolbar/Toolbar.scss
resources/assets/user/src/components/products/ProductBoxesList/components/ProductBox/ProductBox.scss
resources/assets/user/src/components/products/Stepper/Stepper.js
resources/assets/user/src/components/products/Stepper/Stepper.scss
resources/assets/user/src/components/products/Stepper/Stepper.vue
resources/assets/user/src/main.js
resources/assets/user/src/scss/abstracts/_mixins.scss
resources/assets/user/src/scss/abstracts/_variables.scss
resources/assets/user/src/scss/base/_reset.scss
resources/assets/user/src/scss/layout/_spacing.scss
resources/assets/user/src/services/base.service.js
resources/assets/user/src/services/cart.service.js
resources/assets/user/src/utils/constants.js
resources/assets/user/src/utils/helper.js
resources/assets/user/src/views/auth/products/ProductDetailView/ProductDetailView.js
resources/assets/user/src/views/auth/products/ProductDetailView/ProductDetailView.scss
resources/assets/user/src/views/auth/products/ProductDetailView/ProductDetailView.vue
resources/assets/user/src/views/auth/products/ProductDetailView/components/SuccessPopup/SuccessPopup.js
resources/assets/user/src/views/auth/products/ProductDetailView/components/SuccessPopup/SuccessPopup.scss
resources/assets/user/src/views/auth/products/ProductDetailView/components/SuccessPopup/SuccessPopup.vue

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-71](https://duyhuynh55110.atlassian.net/browse/RODAS-71) 
- n/a

feature/RODAS-71: Make add product to cart function

---

database/migrations/2023_03_05_122945_create_order_issues_table.php
database/migrations/2023_03_05_122956_create_order_issue_products_table.php

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-74](https://duyhuynh55110.atlassian.net/browse/RODAS-74) 
- n/a

migration create order_issues, order_issue_products tables

---

.env.dev
docker-compose.yml
docker/app/entrypoint.sh
docker/web/Dockerfile
docker/web/entrypoint.sh
resources/assets/user/src/components/popup/LayoutPopup/LayoutPopup.scss
resources/assets/user/src/views/auth/products/ProductDetailView/components/SuccessPopup/SuccessPopup.scss

**Jira:**
- [https://duyhuynh55110.atlassian.net/browse/RODAS-79](https://duyhuynh55110.atlassian.net/browse/RODAS-79) 
- n/a

feature/RODAS-79: Update docker 
